---
- name: Listar e aplicar atualizações no Windows
  hosts: casa
  gather_facts: yes
  tasks:

    - name: Listar atualizações do Windows Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        state: searched  # Apenas pesquisa
      register: win_update_check

    - name: Mostrar atualizações do Windows Update encontradas
      debug:
        var: win_update_check.updates

    - name: Instalar atualizações do Windows Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: yes
        reboot_timeout: 3600
        state: installed  # Agora instala
      register: win_update_result

    - name: Mostrar atualizações instaladas do Windows Update
      debug:
        var: win_update_result.installed_update_ids

    - name: Listar pacotes desatualizados via Chocolatey
      win_shell: |
        choco outdated
      register: choco_outdated
      args:
        executable: cmd

    - name: Mostrar pacotes desatualizados do Chocolatey
      debug:
        var: choco_outdated.stdout_lines

    - name: Atualizar todos os pacotes via Chocolatey
      win_shell: |
        choco upgrade all -y
      args:
        executable: cmd

    - name: Listar pacotes desatualizados via Winget
      win_shell: |
        winget upgrade
      register: winget_outdated
      args:
        executable: cmd

    - name: Mostrar pacotes desatualizados do Winget
      debug:
        var: winget_outdated.stdout_lines

    - name: Atualizar todos os pacotes via Winget
      win_shell: |
        winget upgrade --all --accept-package-agreements --accept-source-agreements --silent
      args:
        executable: cmd
