---
- name: Executar script PowerShell no Windows
  hosts: casa
  tasks:
    - name: Listar processos
      ansible.windows.win_powershell:
        script: |
          Get-Process | Select-Object Name, ID, CPU | Format-Table -AutoSize
